dh_datastack:
  outputs:
    dev:
      account: nscwcjj-va13130
      database: DH_DATASTACK_ANALYTICS
      password: 5$AMSDMtx3ogspf@
      role: accountadmin
      schema: PUBLIC
      threads: 1
      type: snowflake
      user: gunther
      warehouse: WH_DH_DATASTACK
    prod:
      account: nscwcjj-va13130
      database: DH_DATASTACK_ANALYTICS
      password: 5$AMSDMtx3ogspf@
      role: accountadmin
      schema: PROD
      threads: 1
      type: snowflake
      user: gunther
      warehouse: WH_DH_DATASTACK
  target: dev
dh_datastack_marketing:
  outputs:
    dev:
      account: nscwcjj-va13130
      database: DH_DATASTACK_MARKETING
      password: 5$AMSDMtx3ogspf@
      role: accountadmin
      schema: MARKETING
      threads: 1
      type: snowflake
      user: gunther
      warehouse: WH_DH_DATASTACK
  target: dev
dh_datastack_mdm:
  outputs:
    dev:
      account: nscwcjj-va13130
      database: DH_DATASTACK_MDM
      password: 5$AMSDMtx3ogspf@
      role: accountadmin
      schema: MDM
      threads: 1
      type: snowflake
      user: gunther
      warehouse: WH_DH_DATASTACK
  target: dev
dh_datastack_finance:
  outputs:
    dev:
      account: nscwcjj-va13130
      database: DH_DATASTACK_SALES
      password: 5$AMSDMtx3ogspf@
      role: accountadmin
      schema: SALES
      threads: 1
      type: snowflake
      user: gunther
      warehouse: WH_DH_DATASTACK
  target: dev
jaffle_shop:
  outputs:
    dev:
      account: nscwcjj-va13130
      database: ANALYTICS
      password: 5$AMSDMtx3ogspf@
      role: accountadmin
      schema: PUBLIC
      threads: 1
      type: snowflake
      user: gunther
      warehouse: TRANSFORMING
  target: dev
